
const GlobalAttributeMapping = {
    "preferred_username": "1",
    "realmName": "2",
    "email": "3",
    "groupIds": "4",
    "given_name": "6",
    "family_name": "7",
    "name": "8",
    "employee_id": "10",
    "mobile_number": "11",
    "department": "12",
    "job_title": "13",
    "upn": "14",
    "language": "15",
    "work_country": "16",
    "middle_name": "18",
    "display_name": "19",
    "work_number": "20",
    "fax_number": "21",
    "home_number": "22",
    "pager_number": "23",
    "work_locality": "24",
    "work_street_address": "25",
    "work_address": "26",
    "work_postalcode": "27",
    "work_region": "28",
    "email_verified": "31",
}

module.exports = GlobalAttributeMapping;